// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jctbzxabdmrpzsasxwmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjdGJ6eGFiZG1ycHpzYXN4d21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMTA0MTMsImV4cCI6MjA3Nzc4NjQxM30.6cmBzKy-j2EV16uwVCRyYjqsh0IRUQejzclNd2gh1CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});